png(filename = "polt3.png", width = 480, height = 480)
power3 <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(power3) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subs3 <- subset(power3,power3$Date=="1/2/2007" | power3$Date =="2/2/2007")
subs3$Date <- as.Date(subs3$Date, format="%d/%m/%Y")
subs3$Time <- strptime(subs3$Time, format="%H:%M:%S")
subs3[1:1440,"Time"] <- format(subs3[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subs3[1441:2880,"Time"] <- format(subs3[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subs3$Time,subs3$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(subs3,lines(Time,as.numeric(as.character(Sub_metering_1))))
with(subs3,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
with(subs3,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")
dev.off()