png(filename = "polt2.png", width = 480, height = 480)
power2 <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(power2) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subs2 <- subset(power2,power2$Date=="1/2/2007" | power2$Date =="2/2/2007")
subs2$Date <- as.Date(subs2$Date, format="%d/%m/%Y")
subs2$Time <- strptime(subs2$Time, format="%H:%M:%S")
subs2[1:1440,"Time"] <- format(subs2[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subs2[1441:2880,"Time"] <- format(subs2[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subs2$Time,as.numeric(as.character(subs2$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)") 
title(main="Global Active Power Vs Time")
dev.off()